env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
   no-multi-spaces: 0,
  no-multiple-empty-lines: 0,
  eol-last: 0,
  import/extensions: 0,
  quotes: 0,
  no-console: 0,
  no-undef: 0,
  no-underscore-dangle: 0,
}
